### ISSUE TITLE
autocomplete even

### ISSUE THREAD

**Issue by jiraguha** [shcyiza/G_mapper_JS#1]
https://github.com/shcyiza/G_mapper_JS/blob/11b43769629ee4e93f551cc0768b490fc8245280/app.js#L108

    initMap: function() {
        var autocomplete = new google.maps.places.Autocomplete(this.input_field);
        var self=this;
        autocomplete.addListener('place_changed', function () {
            var directionsService = new google.maps.DirectionsService;
            var directionsDisplay = new google.maps.DirectionsRenderer;
            directionsDisplay.setMap(new google.maps.Map(self.mapNode(), {}));
            _G_M_.calculateAndDisplayRoute(self, directionsService, directionsDisplay);
        });
    },

**Comment by shcyiza** [comment]
merci merci merci
